//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArmServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RobotArmServiceReference.IRobotArmService")]
    public interface IRobotArmService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/Test", ReplyAction="http://tempuri.org/IRobotArmService/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/Test", ReplyAction="http://tempuri.org/IRobotArmService/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/ExecuteCommand", ReplyAction="http://tempuri.org/IRobotArmService/ExecuteCommandResponse")]
        string ExecuteCommand(string clientName, string command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/ExecuteCommand", ReplyAction="http://tempuri.org/IRobotArmService/ExecuteCommandResponse")]
        System.Threading.Tasks.Task<string> ExecuteCommandAsync(string clientName, string command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IRobotArmServiceChannel : RobotArmServiceReference.IRobotArmService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class RobotArmServiceClient : System.ServiceModel.ClientBase<RobotArmServiceReference.IRobotArmService>, RobotArmServiceReference.IRobotArmService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RobotArmServiceClient() : 
                base(RobotArmServiceClient.GetDefaultBinding(), RobotArmServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRobotArmService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RobotArmServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(RobotArmServiceClient.GetBindingForEndpoint(endpointConfiguration), RobotArmServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RobotArmServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RobotArmServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RobotArmServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RobotArmServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RobotArmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string Test()
        {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync()
        {
            return base.Channel.TestAsync();
        }
        
        public string ExecuteCommand(string clientName, string command)
        {
            return base.Channel.ExecuteCommand(clientName, command);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteCommandAsync(string clientName, string command)
        {
            return base.Channel.ExecuteCommandAsync(clientName, command);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRobotArmService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRobotArmService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:54319/RobotArmService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RobotArmServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRobotArmService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RobotArmServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRobotArmService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRobotArmService,
        }
    }
}
